modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="myfirstmod"
version="1.0.0"
displayName="MyFirstMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Никита Паршин, MCreator"

[[dependencies.myfirstmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




